name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [stable, unstable, development-target]
    container:
      image: ghcr.io/elementary/docker:${{ matrix.version }}

    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          apt update
          apt install -y libaccountsservice-dev libgirepository1.0-dev libgnome-desktop-4-dev libgranite-7-dev libadwaita-1-dev libpolkit-gobject-1-dev libpwquality-dev libswitchboard-3-dev meson policykit-1 valac
      - name: Build
        env:
          DESTDIR: out
        run: |
          meson build
          ninja -C build
          ninja -C build install

  lint:
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: io.elementary.vala-lint -d .
